Author: Vadivel, PL (PV48452)

# DICTIONARIES ###############

In [2]:
#Dictionary have key value pairs
eng2sp = dict()
eng2sp = {'one': 'uno', 'two': 'dos', 'three': 'tres'}
print(eng2sp)

{'three': 'tres', 'two': 'dos', 'one': 'uno'}


In [5]:
eng2sp['Zero'] #KEy error. Zero key not present in the dictionary

KeyError: 'Zero'

In [6]:
print(len(eng2sp))
print(eng2sp.keys()) ; print(eng2sp.values())

3
['three', 'two', 'one']
['tres', 'dos', 'uno']


In [14]:
#use of function, dictionary and elif
def caught_speeding(speed, is_birthday="False"): #if second parameter is not passed while calling the function, by default it will take False
    a={'True':[65,85], 'False':[60,80]}
    if (speed > a[is_birthday][1]):
        return "Big Ticket"
    elif (speed > a[is_birthday][0]):
        return "Small Ticket"
    else:
        return "No Ticket"
    
print(caught_speeding(63,"True"))
print(caught_speeding(63,"False"))

No Ticket
Small Ticket


# TUPLE ###############

In [20]:
#tuple is similar to list but not mutable. Values cannot be changed. Entire variable has to be rewritten
t = tuple()
t

()

In [19]:
t = (4,6,8,10)
t

(4, 6, 8, 10)

In [18]:
t = tuple('leaders')
t

('l', 'e', 'a', 'd', 'e', 'r', 's')

In [16]:
t[1] = 'f' #returns error

TypeError: 'tuple' object does not support item assignment

# SET ###############

In [25]:
#set doesnt have duplicate values. It has unique representation of each value
first_set = set(['a','a','a','b','b','a','c','c','d','a','b']) #not showin in variable explorer
second_set = set(['d','e','d','d','e','f'])

In [26]:
first_set.difference(second_set) # A - B

{'a', 'b', 'c'}

In [27]:
first_set.intersection(second_set) # A n B

{'d'}

In [28]:
first_set.union(second_set) # A u B

{'a', 'b', 'c', 'd', 'e', 'f'}

# NUMPY ###############

In [34]:
#numpy - numpy has 1D vectors or 2D matrices
import numpy as np
my_list=[1,2,3]
arr = np.array(my_list) #casting a list into a numpy array

In [36]:
print(my_list, type(my_list), my_list[0])

([1, 2, 3], <type 'list'>, 1)


In [37]:
print(arr, type(arr), arr[0])

(array([1, 2, 3]), <type 'numpy.ndarray'>, 1)


In [38]:
my_list+5   # Error

TypeError: can only concatenate list (not "int") to list

In [40]:
arr+5       # Adds 5 to all elements in arr array

array([6, 7, 8])

In [41]:
arr*5       # Multiplies 5 to all elements in arr array

array([ 5, 10, 15])

In [42]:
a = np.zeros((2,3)) #creating an array of all zeros
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [43]:
b = np.ones((2,2)) #creating an array of all ones
b

array([[ 1.,  1.],
       [ 1.,  1.]])

In [44]:
c = np.full((2,2),6) #fill all the elements with 6
c

array([[6, 6],
       [6, 6]])

In [45]:
d = np.eye(2) #create a 2*2 identity matrix
d

array([[ 1.,  0.],
       [ 0.,  1.]])

In [46]:
e = np.random.rand(2,2) #random numbers from a uniform distribution between 0 and 1. create a 2*2 array filled with random numbers
e

array([[ 0.76834703,  0.97197731],
       [ 0.95407262,  0.43830853]])

In [47]:
e1= np.random.randn(2,2) #random numbers from a normal distribution
e1

array([[ 0.96871331,  0.93070271],
       [-1.06984869,  0.49633907]])

In [49]:
f = np.random.randint(0,3,(2,4)) # create a 2*4 array filled with random numbers - 0 and 2. Start, stop, size
f

array([[2, 2, 1, 1],
       [1, 0, 1, 2]])

In [50]:
g = np.linspace(0,5,11) #gives 11 evenly spaced points between 0 and 5
g

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [51]:
h = np.arange(0,11,2) #similar to range function. this returns an array
h

array([ 0,  2,  4,  6,  8, 10])

In [52]:
###########################################################################################################################

In [59]:
print(e1.max()) #method to find max element in an array
print(e1.min()) #or np.min(e1) - both are same
print(e1.argmax()) #gives the position of max
print(e1.argmin()) #gives the position of min

0.968713310118
-1.06984868797
0
2


In [66]:
e1[-1:]   # Returns the last row

array([[-1.06984869,  0.49633907]])

In [67]:
e1[-1:,1] # Returns the second element in the last row

array([ 0.49633907])

In [68]:
e1[-1:,0:1] # Returns the first element in the last row

array([[-1.06984869]])

In [64]:
e1>0 #This return an array of boolean True / False

array([[ True,  True],
       [False,  True]], dtype=bool)

In [65]:
e1[e1>0] #This returns elements for whose index inside boolean array is positive

array([ 0.96871331,  0.93070271,  0.49633907])

In [60]:
f = f.reshape(4,2) #reashaping array of a particular dimenstion into another dimension
f

array([[2, 2],
       [1, 1],
       [1, 0],
       [1, 2]])

In [61]:
f[0]

array([2, 2])

In [62]:
f[0][1]

2

In [63]:
f[0,1] #Both this line and above line return same result

2

In [76]:
e[:]=3
e

array([[ 3.,  3.],
       [ 3.,  3.]])

In [85]:
slice_of_e = e #This is just a reference to e. if you change e, slice_of_e will also change
slice_of_e_1 = e.copy()
e[1]=4
e

array([[ 3.,  3.],
       [ 4.,  4.]])

In [78]:
slice_of_e

array([[ 3.,  3.],
       [ 4.,  4.]])

In [79]:
slice_of_e_1

array([[ 3.,  3.],
       [ 3.,  3.]])

In [80]:
###########################################################################################################################

In [81]:
np.add(c,b)

array([[ 7.,  7.],
       [ 7.,  7.]])

In [82]:
np.subtract(c,b)

array([[ 5.,  5.],
       [ 5.,  5.]])

In [83]:
np.multiply(c,d)

array([[ 6.,  0.],
       [ 0.,  6.]])

In [84]:
np.sum(f) #sum of all the elements in f

10

In [86]:
np.sum(e, axis=0) #sum of all elements in the columns of e. 

array([ 7.,  7.])

In [87]:
np.sum(e, axis=1) # axis=1 -> sum of row elements

array([ 6.,  8.])

In [88]:
np.sqrt(e)

array([[ 1.73205081,  1.73205081],
       [ 2.        ,  2.        ]])

In [89]:
np.append(c,d)

array([ 6.,  6.,  6.,  6.,  1.,  0.,  0.,  1.])

In [91]:
###########################################################################################################################

In [92]:
import random
random.seed(42)
grade = [np.random.rand() for i in range(0,1000)] #generate 1000 random numbers

In [93]:
grade

[0.945594037558377,
 0.18659958632060902,
 0.9859759183967577,
 0.3253556862702114,
 0.4190360761864681,
 0.3972166644863987,
 0.683213777293569,
 0.8263159297846799,
 0.4809648896516978,
 0.3643496688733687,
 0.4841761919230483,
 0.5122568973393661,
 0.14592013614974797,
 0.15284252186624858,
 0.10701244282624234,
 0.7979103069249239,
 0.14943465207150597,
 0.6287163383414804,
 0.48538726110252484,
 0.318175942153752,
 0.044312709815173656,
 0.673708204413308,
 0.27071031321304484,
 0.7922938901428531,
 0.6684707871889388,
 0.21431934640260986,
 0.8326227153181311,
 0.9492028696822237,
 0.6832260389278075,
 0.11746090252928931,
 0.21560494031170951,
 0.2587526266027603,
 0.24713504229286065,
 0.7922481982656309,
 0.5271559453356847,
 0.3266696353282169,
 0.35525759280613034,
 0.6294658271744454,
 0.35324318561684875,
 0.9473080898326093,
 0.849211340618603,
 0.378471559409746,
 0.032793296222651036,
 0.9855360001913555,
 0.39467356866405445,
 0.9500148272142743,
 0.09626954887481565,
